# Generated by Django 5.0.4 on 2024-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=15)),
                ('gmail', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=10)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
