# Generated by Django 5.0.4 on 2024-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Encargado', 'Encargado')], default='Encargado', max_length=20)),
                ('usuario', models.CharField(max_length=15)),
                ('gmail', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=10)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
