# Generated by Django 5.0.4 on 2024-06-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0002_prueba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
