# Generated by Django 5.0.4 on 2024-06-29 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_user', '0003_alter_usuario_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.AddField(
            model_name='usuario',
            name='terminos_condiciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Encargado', 'Encargado'), ('Seleccionar', 'Seleccionar')], default='Encargado', max_length=20),
        ),
    ]
